### ISSUE TITLE
getting strict error

### ISSUE THREAD

**Issue by vpatel74** [iRayanKhan/homebridge-chamberlain#10]
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
[10/20/2016, 10:53:25 AM] ====================
[10/20/2016, 10:53:26 AM] ERROR LOADING PLUGIN homebridge-chamberlain:
[10/20/2016, 10:53:26 AM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/src/index.js:1:92)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[10/20/2016, 10:53:26 AM] ====================
[10/20/2016, 10:53:26 AM] No plugins found. See the README for information on installing plugins.
[10/20/2016, 10:53:26 AM] Loaded config.json with 1 accessories and 0 platforms.
[10/20/2016, 10:53:26 AM] ---
[10/20/2016, 10:53:26 AM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:60
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Chamberlain' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:251:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:78:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by caseywebdev** [comment]
See previous issues #2, #5, #8, #9
