### ISSUE TITLE
Issuer in trust chain for myqexternal.myqdevice.com expired resulting in 'CERT_HAS_EXPIRED' errors

### ISSUE THREAD

**Issue by brandoniske** [iRayanKhan/homebridge-chamberlain#102]
Mostly an FYI for others who's openers in homekit are non-responsive today.

May 30 07:19:58 netman homebridge[1659]:     at emitOne (events.js:116:13)
May 30 07:19:58 netman homebridge[1659]:     at TLSSocket.emit (events.js:211:7)
May 30 07:19:58 netman homebridge[1659]:     at emitErrorNT (internal/streams/destroy.js:73:8)
May 30 07:19:58 netman homebridge[1659]:     at _combinedTickCallback (internal/process/next_tick.js:139:11)
May 30 07:19:58 netman homebridge[1659]:     at process._tickCallback (internal/process/next_tick.js:181:9)
May 30 07:19:58 netman homebridge[1659]:   name: 'FetchError',
May 30 07:19:58 netman homebridge[1659]:   message: 'request to https://myqexternal.myqdevice.com/api/v4/User/Validate failed, reason: certificate has expired',
May 30 07:19:58 netman homebridge[1659]:   type: 'system',
May 30 07:19:58 netman homebridge[1659]:   errno: 'CERT_HAS_EXPIRED',
May 30 07:19:58 netman homebridge[1659]:   code: 'CERT_HAS_EXPIRED' }

Per https://www.ssllabs.com/ssltest/analyze.html?d=myqexternal.myqdevice.com

USERTrust RSA Certification Authority and AddTrust External CA Root expired even though 
*.myqdevice.com certificate is still good.

Also:
https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

Node v8.17.0
npm 6.13.4
homebridge-chamberlain@1.0.4

**Comment by brandoniske** [comment]
A full upgrade to the latest node/npm/homebridge/chamberlain plugin with new v5 deviceIDs restored functionality.
