### ISSUE TITLE
Offline garage door requires Homebridge restart

### ISSUE THREAD

**Issue by robertlacroix** [iRayanKhan/homebridge-chamberlain#103]
# Explain the issue occuring:
If the door drops off the WiFi, a restart is required to being able to control it again:

```
[6/14/2020, 7:42:46 PM] [Garage Door] Error: invalid response, got HTTP 403: {"code":"403.309","message":"Forbidden","description":"The gateway or hub is offline. Please check the power and network connections."}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[6/14/2020, 7:54:14 PM] [Garage Door] Error: invalid response, got HTTP 403: {"code":"403.309","message":"Forbidden","description":"The gateway or hub is offline. Please check the power and network connections."}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

After that I fixed the door's connectivity, but it still showed as "No Response" in the Home app 30 minutes later. A restart of Homebridge fixed it.

# Expected Result
Accessory recovers from lost connectivity without having to restart Homebridge.

# Info
iOS Version: 13.5.1
Plugin Version: 1.6.0
HomeBridge Version: 1.1.0
Node/Npm Version: 12

**Comment by iRayanKhan** [comment]
That's odd, it should be catching itself. I'll look into this and report back.

**Comment by iRayanKhan** [comment]
@robertlacroix are you using a Pi with rasping by chance?

**Comment by robertlacroix** [comment]
> @robertlacroix are you using a Pi with rasping by chance?

No! It’s running on macOS

**Comment by iRayanKhan** [comment]
Closing: This plugin is now being deprecated. Please use [this](https://github.com/hjdhjd/homebridge-myq) plugin.
