### ISSUE TITLE
FetchError 

### ISSUE THREAD

**Issue by BlueBeedle** [iRayanKhan/homebridge-chamberlain#109]
# Explain the issue occuring:
I get the following error after a few hours, then I reboot causing the issue to go away. However, the issue re-occurs daily. Please note my garage door has been functioning normally through the apple home app. 

Error:  FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/(removed for privacy)/devices/(removed for privacy) failed, reason: getaddrinfo EAI_AGAIN api.

# Expected Result
Since my network is working and my door is functioning properly, my expectation would be to not have a reoccurring error. 

# Info
Plugin Version:1.6.1
HomeBridge Version: 1.1.1
Node.js Version: v12.18.1
Npm Version | v6.14.5

# Log Output:
[7/7/2020, 13:04:33] [Garage Door] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/(removed for privacy) /devices/(removed for privacy) failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
[7/7/2020, 13:05:13] [Garage Door] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/(removed for privacy)/devices/(removed for privacy) failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
[7/7/2020, 13:05:53] [Garage Door] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/(removed for privacy)/devices/(removed for privacy) failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'

**Comment by furenberger** [comment]
EAI_AGAIN is a DNS error.  Do you have anything on your network like a pi.hole or have you changed your router DNS settings?

**Comment by BlueBeedle** [comment]
No network changes and I do not have a pihole. I have an Internet filler on my Orbi but my pi running homebridge is excluded.

**Comment by BlueBeedle** [comment]
I updated my DNS from being my internet provider to google and the issue seems to have resolved.
