### ISSUE TITLE
New Api Change?

### ISSUE THREAD

**Issue by iRayanKhan** [iRayanKhan/homebridge-chamberlain#111]
# Explain the issue occuring:
My garages aren't responding in HomeKit. Chamberlain is probably changing their API, again, or are having an outage.

# Expected Result
Garages should be responding in HomeKit. If anyone can spot a user-agent change that'd be great. I'll merge it instantly. 

# Info
iOS Version: iOS 14 Beta 2
Plugin Version: V1.6.1
HomeBridge Version: V1.1.1
Node/Npm Version: 10.18.0

# Log Output:
```
[7/12/2020, 12:03:16 AM] [Double Garage] { FetchError: request to https://api.myqdevice.com/api/v5/Login failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com api.myqdevice.com:443
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://api.myqdevice.com/api/v5/Login failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com api.myqdevice.com:443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }
[7/12/2020, 12:03:16 AM] [Single Garage] { FetchError: request to https://api.myqdevice.com/api/v5/Login failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com api.myqdevice.com:443
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://api.myqdevice.com/api/v5/Login failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com api.myqdevice.com:443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }

```

**Comment by iRayanKhan** [comment]
Closed. My DNS was acting up.
