### ISSUE TITLE
Fetch Error

### ISSUE THREAD

**Issue by JoMensdorf** [iRayanKhan/homebridge-chamberlain#113]
Hi Guys,

i have the homebridge-chamberlain v1.6.1 on my rasp 3+ with homebridge 1.1.1 and I get a FetchError from time
to time. Sometimes just one in a couple of hours, sometimes ten in a row. The garage opener seems to work anyhow.
Can someone explain why this happens?

[7/17/2020, 23:45:12] [Garage] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/MyAccountNumber/devices/MyDeviceID failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}

Thanks!
Jo

**Comment by iRayanKhan** [comment]
Hey Jo, 
Currently there are 2 planned updates for the plugin. Both betas will be live tonight, so depending on which works, if one works, it will suppress the issue. 

Your garage(s), do start responding after right?

**Comment by JoMensdorf** [comment]
Hey!
Thanks for the reply and the updates!
Yes, it (one) keeps on working.
If you nee a beta tester, I´d be happy to help!
Cheers,
Jo

**Comment by iRayanKhan** [comment]
Just published a new beta with the tag ```rc3```, please let me know if it resolves your issue.

**Comment by Rotox** [comment]
I was also having the same issue and just tried updating to the rc3 version which now gives the following error:

[7/24/2020, 2:53:50 PM] [New Garage Door] Error: invalid response, got HTTP 400: {
    "SecurityToken": "",
    "ReturnCode": "0",
    "ErrorMessage": "please contact customer care, supportID: "xxxxxxxxxxxx",
    "CorrelationId": ""
}
    at /homebridge/node_modules/homebridge-chamberlain/src/api.js:26:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by iRayanKhan** [comment]
@rotox and @JoMensdorf 

Try removing your garage doors from HomeBridge and your config. Run home bridge with just the plugin defined with your username and password and a garage door name. It seems like your deviceID may have changed.

**Comment by JoMensdorf** [comment]
Tried homebridge-chamberlain v1.6.2-beta.1  with this config:

{
            "name": "Garage",
            "username": "Secret1",
            "password": "Secret 2",
            "accessory": "Chamberlain"
        }, 

and:

[7/25/2020, 14:36:42] [Garage] Error: invalid response, got HTTP 400: {
    "SecurityToken": "",
    "ReturnCode": "0",
    "ErrorMessage": "please contact customer care, supportID: "15130798435252029779",
    "CorrelationId": ""
}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:26:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Rotox** [comment]
I received the same error as JoMensdorf using same config. Also when I tried the same config on 1.6.1 it worked but gave me back the same Device ID's so doesn't look like they've changed.

[7/25/2020, 2:37:56 PM] [New Garage Door] Error: invalid response, got HTTP 400: {
    "SecurityToken": "",
    "ReturnCode": "0",
    "ErrorMessage": "please contact customer care, supportID: "  xxxxxxxxxxxxxx",
    "CorrelationId": ""
}
    at /homebridge/node_modules/homebridge-chamberlain/src/api.js:26:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by JoMensdorf** [comment]
Is there anything I can try to help?

**Comment by iRayanKhan** [comment]
So there may be a slight chance you got soft or hard banned. Try removing your garages from HomeKit and the MyQ app, then re-add them if possible

**Comment by JoMensdorf** [comment]
Using homebridge-chamberlain v1.6.1 works fine, so I don´t think I am banned.
But I still get that FetchError.
Jo

**Comment by Rotox** [comment]
Same here v1.6.1 is still working fine for me too except for the FetchError

**Comment by iRayanKhan** [comment]
So to clarify,

Does the fetch error make it go "No Response" in the home app, or will it refetch and try again, and start working?

**Comment by Rotox** [comment]
In my case I believe it's the latter. It must refetch and start working as I don't see "No Response" in the Home App.

**Comment by iRayanKhan** [comment]
So it catches itself and fix's after. I guess it may be their server saying no, but since I don't experience it I don't know how to further proceed. If anyone has any tips please reply.

**Comment by JoMensdorf** [comment]
Same here. Works after the fetch error. 
Maybe the request interval is to small? 
I don´t use any other method to open/close than Siri, so an update every 6hrs would be sufficent for me.

**Comment by JoMensdorf** [comment]
Don´t know if that is something new, but since two days I get this message:
[8/14/2020, 13:54:18] [Garage] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[8/14/2020, 13:54:32] [Garage] desireddoorstate changed from closed to open

But it still works...

**Comment by Rotox** [comment]
Interesting I just looked at my logs and also notice that same message has repeated recently for me too

**Comment by dinof40** [comment]
I've never had this issue before, but since yesterday I've been getting this:

[8/27/2020, 23:54:53] [Garage Door] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/xxxxxx/devices/xxxxxxfailed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'request to https://api.myqdevice.com/api/v5.1/Accounts/xxxxxx/devices/xxxxxxfailed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}

**Comment by iRayanKhan** [comment]
Closing: This plugin is now being deprecated. Please use [this](https://github.com/hjdhjd/homebridge-myq) plugin.
