### ISSUE TITLE
Block-scope declarations syntax error after install

### ISSUE THREAD

**Issue by daniel-ballance** [iRayanKhan/homebridge-chamberlain#2]
DISCLAIMER: Very new to Homebridge, etc. Unable to determine if there's an error in the code or in my installation.

I installed Homebrew for macOS, installed `homebridge-chamberlain` and configured the the `config.json` file per posted instructions. Upon running Homebridge, I received the following error: 

```
[9/20/2016, 8:59:31 AM] ====================
[9/20/2016, 8:59:31 AM] ERROR LOADING PLUGIN homebridge-chamberlain:
[9/20/2016, 8:59:31 AM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/src/index.js:1:92)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[9/20/2016, 8:59:31 AM] ====================
[9/20/2016, 8:59:31 AM] No plugins found. See the README for information on installing plugins.
```

`config.json` file contains:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
        "accessory": "Chamberlain",
        "name": "Garage Door",
        "username": "[insert username here]",
        "password": "[insert password here]"
        }
    ],

    "platforms": [
        {

        }
    ]
}
```

Any help appreciated! Thanks!

**Comment by caseywebdev** [comment]
Ah sorry I should have probably mentioned this in the README, but this plugin uses syntax only supported by node.js >= 6. If you're using Homebrew like you say, you should be able to run `brew update && brew upgrade node` and you'll be on the latest version of node (v6.6.0 at the time of writing).

**Comment by daniel-ballance** [comment]
Thanks Casey. I'm sure this would have fixed the problem, but I believe Homebridge itself is behind the curve on node.js 6.6.0. Error below for reference; thanks for your help! Closing this issue.

```
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

**Comment by caseywebdev** [comment]
You just have to run `npm rebuild` and `mdns` will work properly.

**Comment by caseywebdev** [comment]
Nothing about the homebridge code doesn't work on newer node versions, I'm running `6.6.0` in my house right now.

**Comment by HanSooloo** [comment]
For people who were running into similar problems, documented the process on how to make this work:
1. Install NodeJS 4.x
2. Follow `homebridge` and `homebridge-chamberlain` installation instructions all the way.
3. Update to NodeJS 6.x: http://thisdavej.com/upgrading-to-more-recent-versions-of-node-js-on-the-raspberry-pi/
   1. `curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`
   2. `sudo apt install nodejs`
4. Go to HAP-NodeJS directory and rebuild some modules
   1. `cd /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules`
   2. `npm rebuild mdns`
   3. `npm rebuild bignum --build-from-source`
   4. `npm rebuild ed25519`
   5. `npm rebuild curve25519-n`
