### ISSUE TITLE
Error After installing chamberlain plugin and  restarting homebridge 

### ISSUE THREAD

**Issue by shahavinas** [iRayanKhan/homebridge-chamberlain#20]
I am trying to install homebridge-chamberlain plugin on my raspberry pi. 

Installed chamberlain using 
sudo npm install homebridge-chamberlain
on restarting homebridge, getting the below error.

[2017-6-26 06:21:13] No plugins found. See the README for information on installing plugins.
/opt/node/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Chamberlain' was not registered by any plugin.
    at API.accessory (/opt/node/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/opt/node/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/opt/node/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/opt/node/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

--------------
pi@raspberrypi:~ $ node -v
v8.1.2

----------
config.json.
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
     {
     "accessory": "Chamberlain",
     "name": "Garage Door",
     "username": "MMMMMMMMM@gmail.com",
     "password": "NNNNNNNNNNN"
     }
    ],

    "platforms": [
    ]
}

Thanks

**Comment by shahavinas** [comment]
@caseywebdev
Can you please help.
