### ISSUE TITLE
New and not much experience

### ISSUE THREAD

**Issue by gallen1119** [iRayanKhan/homebridge-chamberlain#23]
I am new to trying to set up Homebridge, so I am sorry if this a totally stupid problem/question.  I am trying to control my garage doors using you homebridge-chamberlain plugin.

I was able to get Homebridge running without plugins and connect via HomeKit. 

MacBook-Pro-8:~ gregoryallen$ homebridge
[8/5/2017, 12:36:06 PM] No plugins found. See the README for information on installing plugins.
[8/5/2017, 12:36:06 PM] Loaded config.json with 0 accessories and 0 platforms.
[8/5/2017, 12:36:06 PM] ---
[8/5/2017, 12:36:06 PM] Loading 0 platforms...
[8/5/2017, 12:36:06 PM] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxx-xx-xxx                         │     
    └────────────┘     
                       
[8/5/2017, 12:36:06 PM] Homebridge is running on port 51826.

I exited homebridge and then installed your plugin and got this:

MacBook-Pro-8:~ gregoryallen$ npm i homebridge-chamberlain
gregoryallen@1.0.0 /Users/gregoryallen
└── homebridge-chamberlain@1.0.1 

I edited my config.json as described., but when I then tried launching Homebridge I get this:

MacBook-Pro-8:~ gregoryallen$ homebridge
[8/5/2017, 12:45:50 PM] No plugins found. See the README for information on installing plugins.
[8/5/2017, 12:45:50 PM] Loaded config.json with 1 accessories and 0 platforms.
[8/5/2017, 12:45:50 PM] ---
[8/5/2017, 12:45:50 PM] Loading 0 platforms...
[8/5/2017, 12:45:50 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Chamberlain' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Thanks for any help you might give to someone just starting out.

**Comment by caseywebdev** [comment]
If you installed `homebridge` with `-g` (global), you'll need to do the same with any plugins. The global flag puts the npm package in the `/usr` directory. I believe what's happening now is you're running `homebridge` from the `/usr` context but you have the chamberlain plugin installed in your home directory, so it doesn't see it as installed.

**Comment by gallen1119** [comment]
That did it! I reinstalled with the `-g` argument and it works perfectly.

**Comment by caseywebdev** [comment]
Great!
