### ISSUE TITLE
Works fine for a few hours, then 'Validate Failed'

### ISSUE THREAD

**Issue by LazzR1** [iRayanKhan/homebridge-chamberlain#25]
Noob here! I have just got this working, but after about an hour or two, it stops working and home bridge reporting the below error. If i restart homebridge, its fine again for a couple of hours. Any ideas?  

Error
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://myqexternal.myqdevice.com/api/v4/User/Validate failed, reason: getaddrinfo ENOTFOUND myqexternal.myqdevice.com myqexternal.myqdevice.com:443',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }

**Comment by caseywebdev** [comment]
This happens occasionally out of no where when (I assume) the MyQ people are making updates to their servers and they go offline temporarily. I've found that eventually it always starts working again without having to restart homebridge.
