### ISSUE TITLE
Error loading Plugin

### ISSUE THREAD

**Issue by psmith3** [iRayanKhan/homebridge-chamberlain#5]
Was wanting to try your plugin in Homebridge, but get the following error: Also, what is different between your plugin and the homebridge-liftmaster?

```
[9/26/2016, 4:32:27 PM] ERROR LOADING PLUGIN homebridge-chamberlain:
stderr
16:32:27
[9/26/2016, 4:32:27 PM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
stderr
16:32:27
    at exports.runInThisContext (vm.js:53:16)
stderr
16:32:27
    at Module._compile (module.js:387:25)
stderr
16:32:27
    at Object.Module._extensions..js (module.js:422:10)
stderr
16:32:27
    at Module.load (module.js:357:32)
stderr
16:32:27
    at Function.Module._load (module.js:314:12)
stderr
16:32:27
    at Module.require (module.js:367:17)
stderr
16:32:27
    at require (internal/module.js:16:19)
stderr
16:32:27
    at Object.&lt;anonymous&gt; (/usr/lib/node_modules/homebridge-chamberlain/src/index.js:1:92)
stderr
16:32:27
    at Module._compile (module.js:413:34)
stderr
16:32:27
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by caseywebdev** [comment]
Check out #2 and #4

**Comment by psmith3** [comment]
Thanks
