### ISSUE TITLE
ECONNRESET Error

### ISSUE THREAD

**Issue by mokrol** [iRayanKhan/homebridge-chamberlain#51]
I've been using this plugin for a few weeks now and had this issue pop up in the last few days:

```
 { FetchError: request to https://myqexternal.myqdevice.com/api/v4/DeviceAttribute/GetDeviceAttribute?AttributeName=doorstate&MyQDeviceId=**<<removed for post>>** failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'FetchError',
  message: 'request to https://myqexternal.myqdevice.com/api/v4/DeviceAttribute/GetDeviceAttribute?AttributeName=doorstate&MyQDeviceId=**<<removed for post>>** failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
```

I updated the plugin yesterday (8/7) hoping that this would fix the issue but no luck. Any help would be greatly appreciated on this.

**Comment by iRayanKhan** [comment]
Try to uninstall and reinstall again, the PR I submitted got merged with the new API so it should work.

**Comment by mokrol** [comment]
Thanks - That fixed it.
