### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Cardo1** [iRayanKhan/homebridge-chamberlain#66]
Good morning,

I'm trying to setup this plugin to access my two Chamberlain garage openers, but when trying to obtain the device IDs I'm getting the following error and HomeBridge is brought down:

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:120:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11

I'm only getting this when trying to run this plugin.  HomeBridge works find without it.  I've also tried using a clean config file with only this platform, but get the same error.

This is on MacOS.  I've updated to Node 12.13 and I'm running the latest version of HomeBridge.  What am I missing?

Ta.

**Comment by Cardo1** [comment]
Me dumb dumb.

This plugin is an accessory, not a platform.  Changing the config to fall under accessory rather than platform solved it.

I leave this here just in case anyone else is silly like me.  :)
