### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by Cardo1** [iRayanKhan/homebridge-chamberlain#69]
Hi there,

I've been using this plugin for the past few days without issue.  However, as of yesterday my garage doors have become unavailable and I have the following error popping up in the log every 10 seconds:

[10/30/2019, 10:56:21 AM] [Garage Door] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:33:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Thoughts?

**Comment by Cardo1** [comment]
Duplicate issue...
