### ISSUE TITLE
No Response in HomeKit

### ISSUE THREAD

**Issue by lherlitz** [iRayanKhan/homebridge-chamberlain#76]
# Explain the issue occuring:
No Response

# Info
iOS Version: iOS 13.2
Plugin Version: 1.0.8
HomeBridge Version: 0.4.50

# Log Output:
```
[11/19/2019, 11:30:30 AM] [Garage Door] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at fetch.then.then.data (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:33:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by iRayanKhan** [comment]
Could you paste your config with info redacted please? Also does this work Remotely or not at all? One last thing, what Hubs and what version are they on? Thanks!

**Comment by spiezer** [comment]
I had the same issue and found out I was blocked from chamberlain's servers.  I wasn't able to access their site or the myq app.  Not sure if it's polling them too much

**Comment by iRayanKhan** [comment]
@spiezer, When I used Pi-Hole Statistics, MYQ was polled the most. In terms of why you were blocked may be due to them cracking down (hope not), or the password being entered wrong, or database migration fail, or anything at this point. Are you now able to use their app? If not, if you ever get the chance, can you make a new account and add your garages to them and see if it works? 
Thanks.

**Comment by spiezer** [comment]
It was working fine yesterday so I believe the entries were correct.  Looks like I can't access myq.com chamberlain.com, etc.  Works fine when I am not using my IP address so it looks like they IP banned me.  I'm still trying to figure out how to get unbanned but the customer service reps have no idea how to help me at the moment.  Unfortunately I'm on a provider that doesn't let me change the IP easily.  I've used other solutions and they stopped working, I haven't been IP banned before!  Pretty odd turn of events.

**Comment by lherlitz** [comment]
> Could you paste your config with info redacted please? Also does this work Remotely or not at all? One last thing, what Hubs and what version are they on? Thanks!

Using the myQ app works perfectly.  No idea how to tell hub type or version. 

```
{
    "bridge": {
        "name": "HOOBS",
        "username": "",
        "port":,
        "pin": ""
    },
    "description": "This file is used for plugin configuration.",
    "accessories": [
        {
            "accessory": "Chamberlain",
            "name": "Garage Door",
            "username": "",
            "password": ""
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "orange",
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "f",
            "sudo": true,
            "standalone": true,
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
            "platform": "config"
        },
        {
            "platform": "Ring",
            "email": "",
            "password": ""
        },
        {
            "platform": "Nest",
            "email": "",
            "password": "",
            "pin": ""
        },
        {
            "platform": "BlinkSecurityPlatform",
            "name": "Blink System",
            "username": "",
            "password": "",
            "discovery": true
        }
    ]
}


```

**Comment by iRayanKhan** [comment]
@spiezer I wonder if the IP banning thing is also whats happening to @lherlitz. One other thing you can try @lherlitz, add the device ID to your config, and see if your providers lets you change IP's.

**Comment by spiezer** [comment]
@iRayanKhan I don't think that's the case since his app is still working.  My app only works when I'm not connected to my IP address. 

I just checked and I had another hub running a hook into MyQ.  That in conjunction with this hack might've triggered something on their end.  It was working great before I got banned though.   

I found a piece of hardware on amazon that hooks into the garage door opener directly.  So hopefully that'll be the end of this game of cat and mouse.  It's [this](https://www.amazon.com/dp/B07QCTN71J/) if you're curious.  Appreciate the dev work!

**Comment by lherlitz** [comment]
Yeah, I’m not ip blocked. My myQ app works perfectly. This is just happening with this plugin.

**Comment by lherlitz** [comment]
How do I find my device id?

**Comment by iRayanKhan** [comment]
@lherlitz When the plugin starts it should spit out a device ID if nothing is listed in the config. I'd recommend making a separate home bridge instance to do this (See Common Issues Wiki). Then adding that parameter to your config may make it work.

**Comment by iRayanKhan** [comment]
Oops didn't mean to close.

**Comment by jasontproject** [comment]
I have seen the same issue for a couple of weeks.
```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at fetch.then.then.data (/home/pi/.nvm/versions/node/v9.11.2/lib/node_modules/homebridge-chamberlain/src/api.js:33:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

Node v9.11.2
├── homebridge@0.4.49
├── homebridge-chamberlain@1.0.5
├── homebridge-dummy@0.3.0
├── homebridge-ifttt@0.3.0
├── homebridge-platform-wemo@1.3.8
├── homebridge-wink3@2.1.0
└── npm@5.6.0


My config:
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "DD:22:3D:E3:CE:32",
    "port": 51825,
    "pin": "403-97-322"
  },
  "description": "Jason's homebridge configuration",
  "accessories": [
    {
      "accessory": "Chamberlain",
      "name": "Garage Door",
      "username": "",
      "password": "",
      "deviceId": "CG0800264586"
    },
    {
      "accessory": "DummySwitch",
      "name": "Trigger Night Light"
    },
    {
      "accessory": "DummySwitch",
      "name": "Trigger Thermostat Resume"
    }
  ],
  "platforms": [
    {
      "platform": "IFTTT",
      "name": "IFTTT",
      "makerkey": "",
      "accessories": [
        {
          "name": "Arlo Switch",
          "buttons": [
            {
              "caption": "Arlo",
              "triggerOn": "arm-arlo",
              "triggerOff": "disarm-arlo"
            }
          ]
        },
        {
          "name": "Withing Switch",
          "buttons": [
            {
              "caption":"Withing",
              "triggerOn":"arm-withing",
              "triggerOff": "disarm-withing"
            }
          ]
        }
      ]
    },
    {
      "platform": "Wink",
      "name": "Wink",
      "client_id": "",
      "client_secret": "",
      "hide_ids": [
      ]
    },
    {
      "platform": "BelkinWeMo",
      "name": "WeMo Platform"
    }
  ]
}
```

**Comment by jasontproject** [comment]
I applied this patch and it fixed the problem: https://github.com/caseywebdev/homebridge-chamberlain/commit/07ca9bd30eb2d37a87780a6a4150a03cb73bc0a1#diff-e1d62d8c4965edf0e532dfa19da0891f

**Comment by iRayanKhan** [comment]
The plugin was updated to add this patch, maybe your version was out of date?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jasontproject** [comment]
I am on 1.0.5, this commit was added after. I typically stick to releases

**Comment by lherlitz** [comment]
I’m not finding a device id anywhere

**Comment by iRayanKhan** [comment]
My garages just went no response. Yikes. Looks like I gotta debug a lot now. API must have changed.

**Comment by iRayanKhan** [comment]
@lherlitz if you don't get a device ID, it must mean you don't have an ethernet gate way (which you don't need and the plugin doesn't utilize).

**Comment by ServusNL** [comment]
Mine is also showing "no response" :( anyway I can help to debug? I only have one device and I'm on the latest version.

**Comment by iRayanKhan** [comment]
I’m looking more into this. If you want to debug, run homebridge with the -D flag and copy and paste the instance messages.

**Comment by Onyx808** [comment]
I ran with he -D flag and all I got was:

`[garage door] desireddoorstate changed from closed to open`

Homekit shows "opening..." but nothing happens =(

**Comment by iRayanKhan** [comment]
@Onyx808 Is there any chance you could clear Persist and Cache? It will mean having to re-add home bridge. If not due to having automations, multiple plugins in an instance, etc, let me know and I know another way. 

Also this happened earlier, but is there a chance your MyQ account was locked? 
An issue posted earlier was where someones account was locked by MyQ due to constant polling, another fix to check may be seeing if the login info is correct.

**Comment by Onyx808** [comment]
I tried rebooting, removing the persist folder, removing the accessory from home kit and reading it, removing all other plugins, and just left home bridge chamberlain and still same thing... I give up.

**Comment by iRayanKhan** [comment]
@Onyx808 Are you willing to try one last thing? iirc I am using the v4Api Branch as that works for me. If that doesn't work it seems your account may have been banned by chamberlain, and making a new one fixes it. 
If anyone needs help installing this plugin, but not the latest version please tag me.

**Comment by Onyx808** [comment]
The myq app works fine, is there a way to send the command via command line and retrieve the error messages?

**Comment by iRayanKhan** [comment]
@Onyx808 Not at the moment, there is a home bridge doorbell plugin if you don't mind installing, see if the notifications can trigger from it, it supports command line triggering and triggers a fake ring every time the plugin loads. 
[Plugin Link](https://github.com/Samfox2/homebridge-doorbell)

**Comment by iRayanKhan** [comment]
Closing for inactivity, if you are still having this issue make a new one or ping me to re-open this one.
