### ISSUE TITLE
EAI_AGAIN error with MyQ API

### ISSUE THREAD

**Issue by Handcuffsofgold** [iRayanKhan/homebridge-chamberlain#82]
# Explain the issue occuring:
Plugin seems to be failing when trying to connect to the MyQ API. Accordingly, control of MyQ via Homekit won't work - sending open/close requests results in no activity.

# Expected Result
Open/close happening when requested via Homekit

# Info
iOS Version: 13
Plugin Version: 1.0.8
HomeBridge Version: 0.4.50
Node/Npm Version: Node.js Version | v10.15.3 / Npm version 6.4.1

# Log Output:

[1/21/2020, 7:17:17 PM] [Garage Door] { FetchError: request to https://api.myqdevice.com/api/v5/accounts/)(REMOVED) failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com api.myqdevice.com:443
    at ClientRequest.<anonymous> (/homebridge/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to https://api.myqdevice.com/api/v5/accounts/(REMOVED), reason: getaddrinfo EAI_AGAIN api.myqdevice.com api.myqdevice.com:443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }

**Comment by Handcuffsofgold** [comment]
Updated my docker container and the problem is gone, so no issue with the plugin. Closing the issue.
