### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by ralstonr** [iRayanKhan/homebridge-chamberlain#84]
# Explain the issue occuring:
Getting error 500 in the log with a set-up that has been working.

# Expected Result
(Give a description of the expected behaviour.)

# Info
iOS Version:N/A
Plugin Version: homebridge-chamberlain v1.0.8
HomeBridge Version: 0.4.50
Node/Npm Version: v10.16.0/v6.9.0

# Log Output:
[1/25/2020, 11:34:26 AM] [number1 Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at res.text.then.body (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[1/25/2020, 11:34:27 AM] [number2 Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at res.text.then.body (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[1/25/2020, 11:34:36 AM] [number1 Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at res.text.then.body (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[1/25/2020, 11:34:37 AM] [number2 Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at res.text.then.body (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
   hoobs : TTY=pts/0 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x
pam_unix(sudo:session): session opened for user root by (uid=0)
[1/25/2020, 11:34:47 AM] [number1 Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}

**Comment by iRayanKhan** [comment]
Hi there,
Do you mind removing the ```"DeviceID"``` field from your config? 
Restarting homebridge will give you a new device ID, and re-enter the working one into your config.

**Comment by ralstonr** [comment]
That fixed it, thank you!
