### ISSUE TITLE
Syntax Error: Unexpected Token

### ISSUE THREAD

**Issue by tarbychark** [iRayanKhan/homebridge-chamberlain#86]
Garage Door has no response in HomeKit and home bridge logs continuously throw this error:

send hb to: 0x0000000007de35a9
connection brokenfalse
null
[2/21/2020, 5:13:08 PM] [Garage Door] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at fetch.then.then.data (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:33:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2/21/2020, 5:13:09 PM] [Garage Door] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at fetch.then.then.data (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:33:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2/21/2020, 5:13:09 PM] [Garage Door] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at fetch.then.then.data (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:33:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2/21/2020, 5:13:10 PM] [Garage Door] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at fetch.then.then.data (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:33:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
send hb to: 0x0000000007de30af
connection brokenfalse
null
retry connect (0) ...: 0x0000000007de30af

This just started happening after a homebridge restart this afternoon.

Confirmed the MyQ app still opens and closes the garage door just fine.

# Info
iOS Version: 13.4 (Beta 2)
Plugin Version: 1.0.8
HomeBridge Version: 4.50
Node/Npm Version:  10.16 / 6.9

**Comment by tarbychark** [comment]
Ended up with an account lockout issue. Changing the password resolved it. Closing issue.

**Comment by tarbychark** [comment]
Reopening, because I’m getting the same error again out of the blue after changing the MyQ password.

**Comment by tarbychark** [comment]
Ok, I figured it out for real this time. Whenever I connect to a non-US VPN on my homebridge server, I get the token error and eventually that leads to an account lockout from Chamberlain. US VPN, no issues. Closing it out again.
